services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
          - ./images:/app/images
          - ./logs:/app/logs

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./images:/images:ro
      - ./static:/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: images_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


