server {
    listen 8080;

    client_max_body_size 6M;

    location = /images/ {
        proxy_pass http://app:8000;
    }

    location /images/ {
        alias /images/;
    }

    location /uploads/ {
        alias /uploads/;
    }

    location /static/ {
        alias /static/;
    }

    location / {
        proxy_pass http://app:8000;
    }
}